name: Container Build CICD

on:
  push:
    branches:
    - 'main'
    # tags:
    #   - '*.*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: uvasds-systems/docker-iss
  IMAGE_TAG: 1.${{ github.run_number }} # GITHUB_RUN_NUMBER }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Set ENV - use this for tags
      #   run: echo "IMAGE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ghcr.io/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: ghcr-io-cleanup-action@main
        with:
          token: ${{ secrets.GHCR_PAT }}
          repository-owner: uvasds-systems
          repository-name: docker-iss
          package-name: docker-iss
          delete-untagged: true
          keep-at-most: 5 # Keep only the latest 5 tagged images